import React from 'react'
import MapSection from '../UI/DirectoryMapUi'

const Maps=()=>{
    let SlotCont=[
        {
            row:[
                {
                    xCordinate:"733.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"45.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"98.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"160.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"213.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"213.09"
                },  
                {
                    xCordinate:"733.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"275.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"328.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"390.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"443.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"505.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"558.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"620.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"620.09"
                },




                {
                    xCordinate:"733.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"673.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"673.09"
                },
                






                {
                    xCordinate:"733.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"735.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"788.09"
                },
                {
                    xCordinate:"733.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"850.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"850.09"
                },






                {
                    xCordinate:"733.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"773.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"813.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"853.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"573.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"613.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"653.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"693.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"453.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"493.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"533.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"293.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"333.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"373.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"413.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"213.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"253.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"93.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"53.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"133.9",
                    yCordinate:"903.09"
                },
                {
                    xCordinate:"173.9",
                    yCordinate:"903.09"
                },




            ]
        }
    ]
    let rowDots=[
        {
            transform: "matrix(1, 0, 0, 1, 844, 142)"
        },
        {
            transform: "matrix(1, 0, 0, 1, 844, 257)"
        },
        {
            transform: "matrix(1, 0, 0, 1, 844, 372)"
        },
        {
            transform: "matrix(1, 0, 0, 1, 844, 487)"
        },
        {
            transform: "matrix(1, 0, 0, 1, 844, 602)"
        },
        {
            transform: "matrix(1, 0, 0, 1, 844, 717)"
        },
        {
            transform: "matrix(1, 0, 0, 1, 844, 832)"
        },
    ]
    return <MapSection data={SlotCont} matrix={rowDots}/>
}

export default Maps